### PR TITLE
A few important things

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Deleted generated/redundant files

### 2nd commit
- Updated the Gradle wrapper from 4.8.1 -> 6.0.1

### 3rd commit
- Updates:
  - Updated Android Studio 3.2.0 -> 3.5.3
  - Updated ``com.google.gms:google-services`` 4.2.0 -> 4.3.3
  - Updated ``io.fabric.tools:gradle`` 1.26.1 -> 1.31.2
  - Updated ``com.github.triplet.gradle:play-publisher`` 2.1.0 -> 2.1.1
  - Updated buildTools 28.0.2 -> 29.0.2
  - Updated google support libraries 27.1.1 -> 28.0.0
  - Update Kotlin 1.2.60 jdk7 -> 1.3.50 jdk8
  - Firebase Ads 17.1.3 -> 17.2.1
  - Firebase Core 16.0.7 -> 16.0.9
  - Firebase Database 16.0.6 -> 16.1.0
  - Firebase Storage 16.0.5 -> 16.1.0
  - Play Services 15.x -> 16.x
  - Gson 2.8.1 -> 2.8.6
  - Google Maps Services 0.9.3 -> 0.9.4
  - Crashlytics 2.9.8 -> 2.10.1
  - Added commons-io
  - Commented out unused libraries

- Other:
  - Added ``strict-version-matcher-plugin`` to help with dependency version conflicts
  - Reorganized build.gradles to be more readable
  - Added Java 8 compatibility
  - Added changelogs to dependencies and libraries

### 4th commit
- Added an .editorconfig
- Adjusted the codestyle to the .editorconfig automatically using Ctrl+Alt+L

### 5th commit
- Migrate from Support to AndroidX libraries
- Update Firebase libraries to their latest
- Update Play Services 16.x -> 17.x
- Glide 4.7.1 -> 4.10.0
- Google Maps Services 0.9.4 -> 0.10.2

### 6th commit
- Clean up the debug manifest
- Delete a bit of redundant code
- Convert anonymous Java expressions to lambdas
- Clean up the XML files

### CODE REVIEW

**Comment by kwatkins** [comment]
@TacoTheDank if you get a chance can you do the updates on current master ... and i'll def merge it, my bad on the delay for this solid commit.

**Comment by TacoTheDank** [comment]
@kwatkins Done, recheck it to see if it's good

**Comment by kwatkins** [comment]
looks great!

**Comment by TacoTheDank** [comment]
@kwatkins Also, you can update the packages in the packages/bin.aarch64, I think most of them have newer versions now. And you should keep the android-file-chooser module up-to-date with its upstream, they may have bugfixes and new features in newer versions to take advantage of. Thanks!

**Pull request merged**
